-- =========================================
-- HealthGuard AI - Complete SQL Queries
-- Hack2skill AI for Everywhere Hackathon
-- =========================================

-- =====================================
-- 1. DATABASE & SCHEMA SETUP
-- =====================================

CREATE DATABASE HEALTHGUARD_DB;
USE DATABASE HEALTHGUARD_DB;

CREATE SCHEMA HEALTHCARE_DATA;
USE SCHEMA HEALTHCARE_DATA;

-- =====================================
-- 2. TABLE CREATION
-- =====================================

CREATE OR REPLACE TABLE PATIENT_RECORDS (
    PATIENT_ID VARCHAR(10),
    NAME VARCHAR(100),
    AGE NUMBER,
    BLOOD_PRESSURE_SYS NUMBER,
    BLOOD_PRESSURE_DIA NUMBER,
    HEART_RATE NUMBER,
    MEDICATION VARCHAR(100),
    LAST_VISIT_DATE DATE,
    LAB_RESULTS VARCHAR(50),
    INSURANCE_ID VARCHAR(20),
    RECORD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =====================================
-- 3. DATA QUALITY VIEWS
-- =====================================

-- View 1: Missing Data Detection
CREATE OR REPLACE VIEW VW_MISSING_DATA AS
SELECT 
    PATIENT_ID,
    NAME,
    CASE WHEN NAME IS NULL OR NAME = '' THEN 1 ELSE 0 END AS MISSING_NAME,
    CASE WHEN AGE IS NULL THEN 1 ELSE 0 END AS MISSING_AGE,
    CASE WHEN BLOOD_PRESSURE_SYS IS NULL THEN 1 ELSE 0 END AS MISSING_BP,
    CASE WHEN HEART_RATE IS NULL THEN 1 ELSE 0 END AS MISSING_HR,
    CASE WHEN MEDICATION IS NULL OR MEDICATION = '' THEN 1 ELSE 0 END AS MISSING_MED,
    CASE WHEN LAST_VISIT_DATE IS NULL THEN 1 ELSE 0 END AS MISSING_VISIT,
    CASE WHEN LAB_RESULTS IS NULL OR LAB_RESULTS = '' THEN 1 ELSE 0 END AS MISSING_LAB,
    CASE WHEN INSURANCE_ID IS NULL OR INSURANCE_ID = '' THEN 1 ELSE 0 END AS MISSING_INS
FROM PATIENT_RECORDS;

-- View 2: Completeness Score
CREATE OR REPLACE VIEW VW_COMPLETENESS_SCORE AS
SELECT 
    PATIENT_ID,
    NAME,
    ROUND(((8 - (MISSING_NAME + MISSING_AGE + MISSING_BP + MISSING_HR + 
                  MISSING_MED + MISSING_VISIT + MISSING_LAB + MISSING_INS)) / 8.0) * 100, 2) AS COMPLETENESS_PERCENT
FROM VW_MISSING_DATA
ORDER BY COMPLETENESS_PERCENT;

-- View 3: Age Anomalies
CREATE OR REPLACE VIEW VW_AGE_ANOMALIES AS
SELECT 
    PATIENT_ID,
    NAME,
    AGE,
    'Invalid Age' AS ISSUE_TYPE,
    CASE 
        WHEN AGE < 0 THEN 'Negative age detected'
        WHEN AGE > 120 THEN 'Unrealistic age (>120)'
        WHEN AGE IS NULL THEN 'Missing age'
        ELSE 'Valid'
    END AS ISSUE_DESCRIPTION
FROM PATIENT_RECORDS
WHERE AGE < 0 OR AGE > 120 OR AGE IS NULL;

-- View 4: Blood Pressure Anomalies
CREATE OR REPLACE VIEW VW_BP_ANOMALIES AS
SELECT 
    PATIENT_ID,
    NAME,
    BLOOD_PRESSURE_SYS,
    BLOOD_PRESSURE_DIA,
    'Abnormal Blood Pressure' AS ISSUE_TYPE,
    CASE 
        WHEN BLOOD_PRESSURE_SYS > 200 THEN 'Critically High Systolic'
        WHEN BLOOD_PRESSURE_SYS < 70 THEN 'Critically Low Systolic'
        WHEN BLOOD_PRESSURE_SYS IS NULL THEN 'Missing BP'
        ELSE 'Other Issue'
    END AS ISSUE_DESCRIPTION
FROM PATIENT_RECORDS
WHERE BLOOD_PRESSURE_SYS > 200 OR BLOOD_PRESSURE_SYS < 70 OR BLOOD_PRESSURE_SYS IS NULL;

-- View 5: Heart Rate Anomalies
CREATE OR REPLACE VIEW VW_HR_ANOMALIES AS
SELECT 
    PATIENT_ID,
    NAME,
    HEART_RATE,
    'Abnormal Heart Rate' AS ISSUE_TYPE,
    CASE 
        WHEN HEART_RATE > 150 THEN 'Tachycardia (Very High)'
        WHEN HEART_RATE < 40 THEN 'Bradycardia (Very Low)'
        WHEN HEART_RATE IS NULL THEN 'Missing Heart Rate'
        ELSE 'Other Issue'
    END AS ISSUE_DESCRIPTION
FROM PATIENT_RECORDS
WHERE HEART_RATE > 150 OR HEART_RATE < 40 OR HEART_RATE IS NULL;

-- View 6: Duplicate Names
CREATE OR REPLACE VIEW VW_DUPLICATE_NAMES AS
SELECT 
    NAME,
    COUNT(*) AS DUPLICATE_COUNT,
    LISTAGG(PATIENT_ID, ', ') AS PATIENT_IDS
FROM PATIENT_RECORDS
WHERE NAME IS NOT NULL AND NAME != ''
GROUP BY NAME
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC;

-- View 7: Outdated Records
CREATE OR REPLACE VIEW VW_OUTDATED_RECORDS AS
SELECT 
    PATIENT_ID,
    NAME,
    LAST_VISIT_DATE,
    DATEDIFF(day, LAST_VISIT_DATE, CURRENT_DATE()) AS DAYS_SINCE_VISIT,
    ROUND(DATEDIFF(day, LAST_VISIT_DATE, CURRENT_DATE()) / 365.0, 1) AS YEARS_SINCE_VISIT
FROM PATIENT_RECORDS
WHERE LAST_VISIT_DATE IS NOT NULL 
  AND DATEDIFF(day, LAST_VISIT_DATE, CURRENT_DATE()) > 365
ORDER BY DAYS_SINCE_VISIT DESC;

-- =====================================
-- 4. ML STATISTICAL ANOMALY DETECTION
-- =====================================

CREATE OR REPLACE VIEW VW_STATISTICAL_ANOMALIES AS
WITH stats AS (
    SELECT 
        AVG(HEART_RATE) AS avg_hr,
        STDDEV(HEART_RATE) AS stddev_hr,
        AVG(BLOOD_PRESSURE_SYS) AS avg_bp,
        STDDEV(BLOOD_PRESSURE_SYS) AS stddev_bp,
        AVG(AGE) AS avg_age,
        STDDEV(AGE) AS stddev_age
    FROM PATIENT_RECORDS
    WHERE HEART_RATE IS NOT NULL 
      AND BLOOD_PRESSURE_SYS IS NOT NULL
      AND AGE IS NOT NULL
)
SELECT 
    P.PATIENT_ID,
    P.NAME,
    P.HEART_RATE,
    P.BLOOD_PRESSURE_SYS,
    P.AGE,
    ROUND(ABS((P.HEART_RATE - S.avg_hr) / NULLIF(S.stddev_hr, 0)), 2) AS HR_ZSCORE,
    ROUND(ABS((P.BLOOD_PRESSURE_SYS - S.avg_bp) / NULLIF(S.stddev_bp, 0)), 2) AS BP_ZSCORE,
    ROUND(ABS((P.AGE - S.avg_age) / NULLIF(S.stddev_age, 0)), 2) AS AGE_ZSCORE,
    CASE 
        WHEN ABS((P.HEART_RATE - S.avg_hr) / NULLIF(S.stddev_hr, 0)) > 2 THEN 'YES'
        ELSE 'NO'
    END AS IS_HR_ANOMALY,
    CASE 
        WHEN ABS((P.BLOOD_PRESSURE_SYS - S.avg_bp) / NULLIF(S.stddev_bp, 0)) > 2 THEN 'YES'
        ELSE 'NO'
    END AS IS_BP_ANOMALY,
    CASE 
        WHEN ABS((P.AGE - S.avg_age) / NULLIF(S.stddev_age, 0)) > 2 THEN 'YES'
        ELSE 'NO'
    END AS IS_AGE_ANOMALY,
    CASE
        WHEN ABS((P.HEART_RATE - S.avg_hr) / NULLIF(S.stddev_hr, 0)) > 3 
          OR ABS((P.BLOOD_PRESSURE_SYS - S.avg_bp) / NULLIF(S.stddev_bp, 0)) > 3
          OR ABS((P.AGE - S.avg_age) / NULLIF(S.stddev_age, 0)) > 3
        THEN 'CRITICAL'
        WHEN ABS((P.HEART_RATE - S.avg_hr) / NULLIF(S.stddev_hr, 0)) > 2 
          OR ABS((P.BLOOD_PRESSURE_SYS - S.avg_bp) / NULLIF(S.stddev_bp, 0)) > 2
          OR ABS((P.AGE - S.avg_age) / NULLIF(S.stddev_age, 0)) > 2
        THEN 'HIGH'
        ELSE 'NORMAL'
    END AS ANOMALY_SEVERITY
FROM PATIENT_RECORDS P
CROSS JOIN stats S
WHERE P.HEART_RATE IS NOT NULL 
  AND P.BLOOD_PRESSURE_SYS IS NOT NULL
  AND P.AGE IS NOT NULL;

-- ML Anomaly Summary
CREATE OR REPLACE VIEW VW_ML_ANOMALY_SUMMARY AS
SELECT 
    'Statistical ML Anomalies Detected' AS METRIC,
    COUNT(*) AS COUNT
FROM VW_STATISTICAL_ANOMALIES
WHERE IS_HR_ANOMALY = 'YES' OR IS_BP_ANOMALY = 'YES' OR IS_AGE_ANOMALY = 'YES'
UNION ALL
SELECT 
    'Critical Severity Anomalies',
    COUNT(*)
FROM VW_STATISTICAL_ANOMALIES
WHERE ANOMALY_SEVERITY = 'CRITICAL'
UNION ALL
SELECT 
    'High Severity Anomalies',
    COUNT(*)
FROM VW_STATISTICAL_ANOMALIES
WHERE ANOMALY_SEVERITY = 'HIGH';

-- =====================================
-- 5. MASTER DASHBOARD
-- =====================================

CREATE OR REPLACE VIEW VW_DATA_QUALITY_DASHBOARD AS
SELECT 
    'Total Patient Records' AS METRIC,
    COUNT(*) AS COUNT,
    '100%' AS PERCENTAGE
FROM PATIENT_RECORDS
UNION ALL
SELECT 
    'Records with Missing Data',
    COUNT(*),
    ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PATIENT_RECORDS)), 1) || '%'
FROM VW_COMPLETENESS_SCORE
WHERE COMPLETENESS_PERCENT < 100
UNION ALL
SELECT 
    'Age Anomalies',
    COUNT(*),
    ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PATIENT_RECORDS)), 1) || '%'
FROM VW_AGE_ANOMALIES
UNION ALL
SELECT 
    'Blood Pressure Anomalies',
    COUNT(*),
    ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PATIENT_RECORDS)), 1) || '%'
FROM VW_BP_ANOMALIES
UNION ALL
SELECT 
    'Heart Rate Anomalies',
    COUNT(*),
    ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PATIENT_RECORDS)), 1) || '%'
FROM VW_HR_ANOMALIES
UNION ALL
SELECT 
    'Duplicate Patient Names',
    COALESCE(SUM(DUPLICATE_COUNT - 1), 0),
    ROUND((COALESCE(SUM(DUPLICATE_COUNT - 1), 0) * 100.0 / (SELECT COUNT(*) FROM PATIENT_RECORDS)), 1) || '%'
FROM VW_DUPLICATE_NAMES
UNION ALL
SELECT 
    'Outdated Records (>1 year)',
    COUNT(*),
    ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PATIENT_RECORDS)), 1) || '%'
FROM VW_OUTDATED_RECORDS;

-- =====================================
-- END OF QUERIES
-- =====================================
